apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
spec:
  ingressClassName: nginx
  rules:
   - host: ip172-18-0-123-cs6h1tqki0og00ajkeag.direct.labs.play-with-k8s.com
     http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: teamcity-server-svc
                port: 
                  number: 8111
          - pathType: Prefix
            path: /agent
            backend:
              service:
                name: teamcity-agent-svc
                port: 
                  number: 9090

