apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
spec:
  ingressClassName: nginx
  rules:
   - host: tc-local.com
     http:
        paths:
          - pathType: Exact
            path: /
            backend:
              service:
                name: teamcity-server-svc
                port: 
                  number: 8080
          - pathType: Exact
            path: /agent
            backend:
              service:
                name: teamcity-agent-svc
                port: 
                  number: 9090

