apiVersion: v1
kind: Service
metadata: 
  name: teamcity-server
spec:
  selector:
    app: teamcity-server
  ports:
    - name: tcserv
      protocol: TCP
      port: 80
      targetPort: 8111
  # clusterIP: 10.101.79.60
  # clusterIPs:
    # - 10.101.79.60
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster