apiVersion: v1
kind: Service
metadata: 
  name: teamcity-server-svc
spec:
  selector:
    app: teamcity-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 8111
      targetPort: 8111
  type: NodePort
