---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-pv-claim
  labels:
    app: teamcity-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi