image: gitlab/gitlab-ce:17.3.5-ce.0
name: gitlab-server
servicePorts:
  - name: glhttp
    protocol: TCP
    port: 80
    targetPort: 80
  - name: glhttps
    protocol: TCP
    port: 443
    targetPort: 443
  - name: glssh
    protocol: TCP
    port: 22
    targetPort: 22
  
ports:
  - name: http
    containerPort: 80
    protocol: TCP
  - name: ssh
    containerPort: 22
    protocol: TCP
  - name: https
    containerPort: 443
    protocol: TCP
volumeMounts:
  - name: gitlab-config
    mountPath: /etc/gitlab
  - name: gitlab-logs
    mountPath: /var/log/gitlab
  - name: gitlab-data
    mountPath: /var/opt/gitlab
volumes:
  - name: gitlab-config
    hostPath:
      path: /mnt/gl_data/config
      type: DirectoryOrCreate
  - name: gitlab-logs
    hostPath:
      path: /mnt/gl_data/logs
      type: DirectoryOrCreate
  - name: gitlab-data
    hostPath:
      path: /mnt/gl_data/data
      type: DirectoryOrCreate