secret:
    id_ed25519: ENC[AES256_GCM,data:70nzWVC4o8rK7cF66/BpJSuKZji12wnlMDR82FkNjiqLXbllS+COTP2vvLK5+d7rD83Xrfc02C9Vtos7EugWhbZwmDCVPbzSyHjUtcEcB2JEIaZOT0X7g7diX9iHfUVNaTiaFP9VClGs89AgnB6euy/8nmUE8M18bDhePCdxEWjEM2fPF8Fsnkh9hP1afBazXn9GWeRDJVfEcPa4guo35gJ0z3jjJYOgmJe9r8wlAgIbbdo3N8kFqQ0CBIWXXpT08IfwSTuWcmbKEIsOJlzwNYYn0C4If/21FCAulHzBnzrnCdC7ef030F0HmhfuWAGSH+4MTRFHtb26dFNVnUa87Gdfd7dy3QLWxaa4wSVaHfR+ej37DCRSX/ydUPpwhdWKOdLtPfkesgdj3IRpMIM8LAQRI60lOA/hgBrlGDObpDRnud2OqUM2t2a5y3XfPRAE6/PbRDrFu0lHSgLgfiFB2/IRSdcVFu1An7/ovpvWGMxc5A6FhwiBOmCfFeQ3/F2c7IXtJjSy4XCtInnD48VhH9npJaI=,iv:nbuHHO388jfClLc0NYp0+RnrM3v+8DeZ9O2VZC6E2Uc=,tag:ecGEW/8ZFRrRIPF6hyKvWg==,type:str]
    password: ENC[AES256_GCM,data:y8O/QwoO,iv:+JDF2OgNmpdpz8VwCnN4QuobhYVWD+KyFtIeMIEO5ds=,tag:VEzhL4qQuD7ojaacjBx4nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-13T20:16:20Z"
    mac: ENC[AES256_GCM,data:ieRkVwY/qliXzeL0p16KO/A+yL9WCvdy4rhKA+7622Wb1dwBbv2AVSQhzf2crTdvduyDo/5Nvq9n52UqZyanAlOLOKUEyQ6j/mpO60A/ifBTakhPbxZkp/lDkCGkPw6FNDFkLVevJdCtUwMzWLc4ov4KaQn2fAqnDUvfXSIwSRA=,iv:DeBx3pzrYe0dr3nvRWbBhjQJcV8js8hzTubdunqjBF0=,tag:nrVIgwDdDS6XYYgLz1fUvg==,type:str]
    pgp:
        - created_at: "2024-12-13T20:16:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAzGXhw3R/kO4AQv9H3ijdt3dM896vpCj+ZYXaZPPBILv6v9b4xD5yaAcxBuR
            QKX2ihtWe4LWKAXioItdywMSAe1vXalIHIFuMBr0hSYz+3Al0XaEhceeKYL3U1rG
            uMNQ2AfRk6Rd7k0htiXGyoXod5dzCi/sc5KV/NhXx2gPkjACZAkJ8loNzxnlch5F
            PdYs7nuymXJomeMkJ0+T78qHnm17naGriM7u1aLHPuHXODZPRmFTpmrJ48/QLi/O
            llBpogxczxHI0R9a7pPq2nUMw40r85Xp6Wi4sfJnjtOKJba+13JJHgURvrTI6jo8
            24SqSAV38Rla6ZqZT2aMmbuZIn12KiQaz8n5OeMDConwrha7BZlCbQi0o1/INvzG
            gVjCG7ajrTczgLuedj/9NXaGKH9h426aPTOGeVvs7VT03Ueb4oqsd0ZxYa+5W50c
            5wf6lyOF9C5acwInpJsTkA1/ABLk1AO+1pD0/olDAU1pLiR2N9LyEdUpX7xezVQC
            TmHgVb85qNTHlxCP22e10l4BwPTtXBT9G5LxW25ZKMdQTITeiYkVr7q83eGBeVaF
            6QNseqb+KtZqApVcbQIykjm1qbiNhr87giqsxq/N5DGR5rafASUxPopm4u2eZxqD
            LAvBLDiVi8MIISrOhk+H
            =w+mD
            -----END PGP MESSAGE-----
          fp: 1C6A233A1F8A3CA8908CC4D2F14492A4DF4A2A1A
    unencrypted_suffix: _unencrypted
    version: 3.9.1
