image: "jetbrains/teamcity-server:2024.07.2"
name: teamcity-server

env:
- name: MYSQL_PASSWORD
  sname: teamcity-server-secret
  skey: password

servicePorts:
  - port: 80
    targetPort: 8111

ports:
  - containerPort: 8111
    protocol: TCP
    name: http

volumeMounts:
  - mountPath: /data/teamcity_server/datadir
    name: db-volume
  - mountPath: /opt/teamcity/.ssh/
#    subPath: id_ed25519
    name: privkey
volumes:
  - name: db-volume
    hostPath:
      path: /mnt/tc_data
      type: DirectoryOrCreate
  - name: privkey
    secret:
      secretName: secret

ingress:
  enabled: true
  className: nginx
  hosts:
  - host: tc.tc-local.home
    pathType: Prefix
    path: "/"
    name: teamcity-server-svc
    number: 80
  - host: gl.tc-local.home
    pathType: Prefix
    path: "/"
    name: gitlab-server-svc
    number: 80

database:
  type: mysql # или postgres в зависимости от вашей базы данных (mysql или postgresql)
  host: mysql-server # имя сервиса для MySQL или postgresql для PostgreSQL 
  port: 3306 # или 5432 для PostgreSQL 
  name: teamcity # имя базы данных, созданной ранее 
  user: teamcity # пользователь базы данных 

configMap:
  datadirConfig:
    database.properties: |
      connectionUrl=jdbc:mysql://{{ $.Values.database.host }}/{{ .Values.database.name}}?allowPublicKeyRetrieval=true&useSSL=false
      connectionProperties.user={{ $.Values.database.user }}
      connectionProperties.password={{ $.Values.database.password }}
      maxConnections=50
